Repository godeka/kiki_kiosk, pull requests merged in 2024-05, with the labels that each got.

#4 #3 in out screen
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/InOutScreen.js
  frontend/src/components/Question.js
  frontend/src/components/WelcomeScreen.js
  frontend/src/components/button/BoxButton.js
  frontend/src/components/button/GoBackButton.js
Labels: feature ⚙️, Frontend, style ✨

#16 Chore: CORS 설정
  .idea/compiler.xml
  .idea/modules/oopAssignment.main.iml
  src/main/java/oop/kiosk/oopassignment/config/WebConfig.java
Labels: feature ⚙️, Backend

#22 Feature: Register 관련 API 작성
  build/classes/java/main/oop/kiosk/oopassignment/menu/domain/Menu.class
  build/classes/java/main/oop/kiosk/oopassignment/menu/dto/MenuCreateRequest.class
  build/classes/java/main/oop/kiosk/oopassignment/menu/dto/MenuResponse.class
  src/main/java/oop/kiosk/oopassignment/register/RegisterController.java
  src/main/java/oop/kiosk/oopassignment/register/RegisterRepository.java
  src/main/java/oop/kiosk/oopassignment/register/RegisterService.java
  src/main/java/oop/kiosk/oopassignment/register/domain/Register.java
  src/main/java/oop/kiosk/oopassignment/register/dto/LoginRequest.java
  src/main/java/oop/kiosk/oopassignment/register/dto/PasswordChangeRequest.java
Labels: feature ⚙️
